# Generated by Django 3.0.4 on 2020-05-04 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_branch', models.CharField(max_length=20, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Kab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_kab', models.CharField(max_length=5, verbose_name='Номер кабинета')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Branch', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Mobile_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numder_mobile_phone', models.CharField(max_length=13, unique=True, verbose_name='Номер моб. телуфона')),
            ],
            options={
                'verbose_name': 'Номер мобильного телефона',
                'verbose_name_plural': 'Номера мобильных телефонов',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=20, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=20, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Work_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_work_phone', models.CharField(max_length=10, unique=True, verbose_name='Городской телефон')),
            ],
            options={
                'verbose_name': 'Номер городского телефона',
                'verbose_name_plural': 'Номера городских телефонов',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_delete', models.BooleanField(default=False)),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('kab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Kab', verbose_name='Кабинет')),
                ('mobile_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Mobile_Phone', verbose_name='Мобильный телефон')),
                ('monitor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Monitor', verbose_name='Монитор')),
                ('name_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Role', verbose_name='Роль')),
                ('pc', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.PC', verbose_name='ПК')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Post', verbose_name='Должность')),
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Printer', verbose_name='Принтер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Work_Phone', verbose_name='Городской телефон')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='kab',
            name='work_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Work_Phone', verbose_name='Городской телефон'),
        ),
    ]
