# Generated by Django 3.0.4 on 2020-03-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixed_assets',
            options={'verbose_name': 'Основное средство', 'verbose_name_plural': 'Основыные средства'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': 'Монитор', 'verbose_name_plural': 'Мониторы'},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={'verbose_name': 'ПК', 'verbose_name_plural': 'ПК'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер', 'verbose_name_plural': 'Принтеры'},
        ),
        migrations.AlterModelOptions(
            name='type_catridge',
            options={'verbose_name': 'Тип катриджа', 'verbose_name_plural': 'Типы катриджей'},
        ),
        migrations.AddField(
            model_name='pc',
            name='inv_number',
            field=models.CharField(default='null', max_length=10, verbose_name='Инвентарынй номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monitor',
            name='fixed_assets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Fixed_assets', verbose_name='Инвентарный № монитора'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='fixed_assets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Fixed_assets', verbose_name='Инвентарный № ПК:'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='name_pc',
            field=models.CharField(max_length=50, verbose_name='Имя ПК'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='fixed_assets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Fixed_assets', verbose_name='Принтер'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='type_catridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Type_catridge', verbose_name='Тип катриджа'),
        ),
    ]
