# Generated by Django 3.0.4 on 2020-03-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed_assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_assets', models.CharField(max_length=50, verbose_name='Наименование')),
                ('inv_number', models.CharField(max_length=10, verbose_name='Инвентарынй номер')),
            ],
        ),
        migrations.CreateModel(
            name='Type_catridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_catridge', models.CharField(max_length=20, verbose_name='Наименование катриджа')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_printer', models.CharField(max_length=20, verbose_name='Наименование принтера')),
                ('inv_number', models.CharField(max_length=10, verbose_name='Инвентарынй номер')),
                ('fixed_assets', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Fixed_assets')),
                ('type_catridge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Type_catridge')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pc', models.CharField(max_length=50, verbose_name='Наименование ПК')),
                ('ip_address', models.CharField(max_length=10, verbose_name='Ip адрес')),
                ('os', models.CharField(max_length=10, verbose_name='Операционная система')),
                ('fixed_assets', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Fixed_assets')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_monitor', models.CharField(max_length=50, verbose_name='Наименование монитора')),
                ('inv_number', models.CharField(max_length=10, verbose_name='Инвентарынй номер')),
                ('fixed_assets', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Fixed_assets')),
            ],
        ),
    ]
