# Generated by Django 3.0.4 on 2020-05-04 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='BIT_request_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=10, verbose_name='Наименование категории')),
                ('note', models.CharField(max_length=200, verbose_name='Примечание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestBIT.BIT_request_category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='BIT_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now=True, verbose_name='Дата создания заявки')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('date_close', models.DateTimeField(auto_now=True, verbose_name='Дата закрытия заявки')),
                ('BIT_request_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requestBIT.BIT_request_category', verbose_name='Тип заявки')),
                ('name_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_user', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requestBIT.Status', verbose_name='Статус')),
                ('user_executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_executor', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник BIT:')),
            ],
            options={
                'verbose_name': 'Заявку',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
