# Generated by Django 3.0.4 on 2020-03-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_branch', models.CharField(max_length=20, verbose_name='Отдел')),
            ],
        ),
        migrations.CreateModel(
            name='Kab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_kab', models.CharField(max_length=5, verbose_name='Номер кабинета')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numder_mobile_phone', models.CharField(max_length=13, verbose_name='Номер моб. телуфона')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=20, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_role', models.CharField(max_length=20, verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Work_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_work_phone', models.CharField(max_length=10, verbose_name='Городской телефон')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_delete', models.BooleanField(default=False)),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('kab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Kab')),
                ('mobile_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Mobile_Phone')),
                ('monitor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Monitor')),
                ('name_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Role')),
                ('pc', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.PC')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Post')),
                ('printer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Printer')),
                ('work_phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Work_Phone')),
            ],
        ),
        migrations.AddField(
            model_name='kab',
            name='work_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Work_Phone'),
        ),
    ]
