# Generated by Django 3.0.4 on 2020-03-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile_Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numder_mobile_phone', models.CharField(max_length=13, verbose_name='Номер моб. телуфона')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_post', models.CharField(max_length=20, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_delete', models.BooleanField(default=False)),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('login', models.CharField(max_length=20, verbose_name='Логин')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('mobile_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Mobile_Phone')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Post')),
            ],
        ),
    ]
