# Generated by Django 3.0.4 on 2020-03-31 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0002_auto_20200331_1214'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='kab',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='mobile_phone',
            options={'verbose_name': 'Номер мобильного телефона', 'verbose_name_plural': 'Номера мобильных телефонов'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='work_phone',
            options={'verbose_name': 'Номер городского телефона', 'verbose_name_plural': 'Номера городских телефонов'},
        ),
        migrations.AlterField(
            model_name='kab',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Branch', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='kab',
            name='work_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Work_Phone', verbose_name='Городской телефон'),
        ),
        migrations.AlterField(
            model_name='mobile_phone',
            name='numder_mobile_phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='Номер моб. телуфона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Kab', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Mobile_Phone', verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='monitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Monitor', verbose_name='Монитор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.PC', verbose_name='ПК'),
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Post', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='printer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.Printer', verbose_name='Принтер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Work_Phone', verbose_name='Городской телефон'),
        ),
        migrations.AlterField(
            model_name='work_phone',
            name='number_work_phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Городской телефон'),
        ),
    ]
