# Generated by Django 3.0.4 on 2020-03-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='BIT_request_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=10, verbose_name='Наименование категории')),
                ('note', models.CharField(max_length=200, verbose_name='Примечание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requestBIT.BIT_request_category', verbose_name='Родительская категория')),
            ],
        ),
        migrations.CreateModel(
            name='BIT_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now=True, verbose_name='Дата создания заявки')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('date_close', models.DateTimeField(auto_now=True, verbose_name='Дата закрытия заявки')),
                ('BIT_request_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requestBIT.BIT_request_category')),
            ],
        ),
    ]
