# Generated by Django 3.0.4 on 2020-03-31 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('requestBIT', '0002_auto_20200330_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bit_request',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='bit_request_category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='bit_request',
            name='BIT_request_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requestBIT.BIT_request_category', verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='bit_request',
            name='date_start',
            field=models.DateField(verbose_name='Дата создания заявки'),
        ),
        migrations.AlterField(
            model_name='bit_request',
            name='name_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_user', to='users.User', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='bit_request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requestBIT.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bit_request',
            name='user_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_executor', to='users.User', verbose_name='Ответственный сотрудник BIT:'),
        ),
    ]
