# Generated by Django 3.0.4 on 2020-03-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('requestBIT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit_request',
            name='name_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_user', to='users.User'),
        ),
        migrations.AddField(
            model_name='bit_request',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='requestBIT.Status'),
        ),
        migrations.AddField(
            model_name='bit_request',
            name='user_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_executor', to='users.User'),
        ),
    ]
